obj-m+=listdemo.o

all:
	make -C /home/user/workspace/linuxO M=${PWD} modules ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-
clean:
	make -C /home/user/workspace/linuxO M=${PWD} clean ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-